start =
    expression

expression =
    ws a:atom ws
        { return a; }
    /
    ws "(" a:expression* ")" ws
        { return a; }
    /
    ws "'" a:expression
        { return ["quote", a]; }

wschar =
    [ \t\r\n]

ws =
    wschar* (";;" (!"\n" .)* wschar*)*

validchar =
    [0-9a-zA-Z_?!+\-=@#$%^&*/.]

atom =
    ( sign:[+-]? intchars:[0-9]+ )
        { return parseInt(sign + intchars.join(""), 10); }
    /
    chars:validchar+
        { return chars.join(""); }